upgrade to sbt 1.3.0 (#354)
* upgrade to sbt 1.3.0

Note: I configured sbt to fork tests, because cpgserver/test started to fail
the build - while the tests were green, it threw a random
'NoClassDefFoundError: akka/event/Logging$Info$', even though that
seems to be on the classpath.

* sbt launcher location